// AUTO-GENERATED by scripts/generate-projects.mjs — do not edit by hand.
// Re-run: npm run generate-projects.  Curate + add details in projects.ts.

export type GeneratedProject = {
  slug: string
  title: string
  blurb: string
  tech: string[]
  image: string
  live: string
  source: string
  stars: number
}

export const generatedProjects: GeneratedProject[] = [
  {
    "slug": "Discord-Example",
    "title": "Discord Example",
    "blurb": "",
    "tech": [
      "JavaScript"
    ],
    "image": "/projects/gh-discord-example.png",
    "live": "",
    "source": "https://github.com/BenjiCollege/Discord-Example",
    "stars": 1
  },
  {
    "slug": "BenjiCollege",
    "title": "BenjiCollege",
    "blurb": "Hi this is my personal repository about me",
    "tech": [],
    "image": "/projects/gh-benjicollege.png",
    "live": "",
    "source": "https://github.com/BenjiCollege/BenjiCollege",
    "stars": 0
  },
  {
    "slug": "doyouwannagooutwithme-main",
    "title": "Doyouwannagooutwithme Main",
    "blurb": "",
    "tech": [
      "CSS",
      "HTML"
    ],
    "image": "/projects/gh-doyouwannagooutwithme-main.png",
    "live": "https://doyouwannagooutwithme-main.vercel.app",
    "source": "https://github.com/BenjiCollege/doyouwannagooutwithme-main",
    "stars": 0
  },
  {
    "slug": "photo-web",
    "title": "Photo Web",
    "blurb": "",
    "tech": [
      "JavaScript",
      "HTML",
      "CSS"
    ],
    "image": "",
    "live": "",
    "source": "https://github.com/BenjiCollege/photo-web",
    "stars": 0
  },
  {
    "slug": "javascriptGame",
    "title": "JavascriptGame",
    "blurb": "",
    "tech": [
      "JavaScript",
      "SCSS",
      "CSS",
      "HTML"
    ],
    "image": "",
    "live": "",
    "source": "https://github.com/BenjiCollege/javascriptGame",
    "stars": 0
  },
  {
    "slug": "calculator-dev",
    "title": "Calculator Dev",
    "blurb": "",
    "tech": [
      "HTML",
      "JavaScript",
      "CSS"
    ],
    "image": "",
    "live": "",
    "source": "https://github.com/BenjiCollege/calculator-dev",
    "stars": 0
  },
  {
    "slug": "python-adventure-game",
    "title": "Python Adventure Game",
    "blurb": "",
    "tech": [
      "Python",
      "PowerShell",
      "Batchfile"
    ],
    "image": "/projects/gh-python-adventure-game.png",
    "live": "",
    "source": "https://github.com/BenjiCollege/python-adventure-game",
    "stars": 0
  },
  {
    "slug": "draft-api",
    "title": "Draft API",
    "blurb": "",
    "tech": [
      "JavaScript",
      "SCSS",
      "HTML",
      "CSS"
    ],
    "image": "",
    "live": "",
    "source": "https://github.com/BenjiCollege/draft-api",
    "stars": 0
  },
  {
    "slug": "node-2-main",
    "title": "Node 2 Main",
    "blurb": "",
    "tech": [
      "JavaScript"
    ],
    "image": "/projects/gh-node-2-main.png",
    "live": "",
    "source": "https://github.com/BenjiCollege/node-2-main",
    "stars": 0
  },
  {
    "slug": "calculator",
    "title": "Calculator",
    "blurb": "",
    "tech": [
      "JavaScript",
      "SCSS",
      "CSS",
      "HTML"
    ],
    "image": "/projects/gh-calculator.png",
    "live": "",
    "source": "https://github.com/BenjiCollege/calculator",
    "stars": 0
  }
]
